name: sightline_app
description: "A cross-platform AI application for image captioning"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  http: ^1.1.0
  flutter_tts: ^3.8.3
  path_provider: ^2.1.1
  provider: ^6.1.5
  flutter_dotenv: ^5.1.0
  camera: ^0.10.5+5
  permission_handler: ^11.0.1
  intl: ^0.18.1
  flutter_bootstrap: 2.0.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env